### ISSUE TITLE
Remove parenthesis automagically

### ISSUE THREAD

**Issue by coder3101** [Megaxela/QCodeEditor#23]
**Is your feature request related to a problem? Please describe.**

Whenever you delete an opening bracket or parentheses as a typo, it won't delete the corresponding closing bracket.

**Describe the solution you'd like**

Let's say the cursor is at the `|`
In `a(|)b` and `a()|b`, when you press Backspace, it should become `ab`. but in `a(|bcd)e` when you press Backspace it should still be `a|bcd)e`.

**Describe alternatives you've considered**
none

**Additional context**
none

Originally requested here https://github.com/coder3101/cp-editor2/issues/42

**Comment by ouuan** [comment]
I suggest making it optional.

**Comment by coder3101** [comment]
> I suggest making it optional.

Surely!! @Megaxela can provide a public method like `setAutoRemoveParenthesis(bool)`.

**Comment by Megaxela** [comment]
Sounds nice. I'll implement this soon.

**Comment by ns10-1999** [comment]
> Sounds nice. I'll implement this soon.

Upto when (I mean how much time) can we expect it do be done?

**Comment by ouuan** [comment]
> > Sounds nice. I'll implement this soon.
> 
> Upto when (I mean how much time) can we expect it do be done?

I have no idea, but CP Editor will use Scintilla soon.

**Comment by coder3101** [comment]
> > > Sounds nice. I'll implement this soon.
> > 
> > 
> > Upto when (I mean how much time) can we expect it do be done?
> 
> I have no idea, but CP Editor will use Scintilla soon.

Yes but I I would still use this Editor because of rich theme support. I will propose some PR in coming days to make this and some other important features work.

**Comment by coder3101** [comment]
Redirected to : https://github.com/ouuan/QCodeEditor/issues/3
