### ISSUE TITLE
Feature request: Find & Replace

### ISSUE THREAD

**Issue by ouuan** [Megaxela/QCodeEditor#24]
Finding and replacing are basic functions of an editor, but seems not implemented yet.

It would be better if regexp is supported (which should be optional).

**Comment by Megaxela** [comment]
I was thinking about implementing this feature. But I came to the conclusion that this should be implemented by the consumer of the library. But considering that this code would be a boilerplate, it really is worth implementing such functionality.

**Comment by ouuan** [comment]
You are right, it should be implemented by the consumer. QTextDocument already has some APIs.
