### ISSUE TITLE
Comment and Uncomment selection using CTRL+/

### ISSUE THREAD

**Issue by coder3101** [Megaxela/QCodeEditor#27]
Almost all modern editor have a feature to comment and Uncomment a selection of test using `CTRL+/`. You should provide a default implementation of this behaviour and also a way to change the the toggle key. 

Maybe a function like `setToggleCommentShortcut(..);` would do it. If set to nullptr means that Disable comments toggle otherwise any key combination.

Originally asked here : https://github.com/coder3101/cp-editor2/issues/59

**Comment by Megaxela** [comment]
Sounds like really useful function. I'll place it in list of tasks to implement!

**Comment by coder3101** [comment]
Already implemented in https://github.com/ouuan/QCodeEditor

We have shifted to that repository, it may be a good idea if you could cherry pick his commits and add this, but for now I am closing this issue
