### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by redtide** [Megaxela/QCodeEditor#42]
I see no updates from an year and half, if so it's a pity, the project looks interesting.

**Comment by justxi** [comment]
I think the most recent version is https://github.com/arucil/QCodeEditor.
I made a few changes to build it against Qt 6.

**Comment by justxi** [comment]
Added an option to compile a shared library, an install target, versioning and configuration files to use "find_package".
-> https://github.com/justxi/QCodeEditor/

EDIT: @redtide Maybe you want to change the title to "Dead project? - No =)".

**Comment by redtide** [comment]
I think close it is enough, but be aware that I can always reopen it again! ---horror music here---
