### ISSUE TITLE
Feature Request: Add Brackets matching or highlighting

### ISSUE THREAD

**Issue by coder3101** [Megaxela/QCodeEditor#7]
This will be good feature to add, it really annoys the end-use if they use a code editor which does not highlights which braces closes which blocks in the code, specially in the case of nested blocks.

It should be simple to add, I wish to have a behavior like this:
```
if(current_code_cursor_is on_braces or on_parenthesis){
    // highlight or make the matching and this current braces or parenthesis bold. 
}
```

**Comment by coder3101** [comment]
Seems like this is already implemented https://github.com/coder3101/QCodeEditor/blob/6c6ad9257dd11dc35f4a3bccc3ca35108305e0a7/src/internal/QCodeEditor.cpp#L257 but does not work (at least on my machine). Could you confirm?

**Comment by Megaxela** [comment]
Well, I'll be able to check this tomorrow, but I remember, that I'd already implemented this feature. It may not work because of some theme magic. I guess this ticket can be converted into bug.

**Comment by coder3101** [comment]
@Megaxela any updates on this?

**Comment by Megaxela** [comment]
@coder3101 Hi, sorry for delay. I found out error and going to fix it.
